---
version: '3.8'
services:
  django:
    build:
      target: production
    image: django-prod-${PROJECT_NAME}
    container_name: django-prod-${PROJECT_NAME}
    environment:
      DD_DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - database
  database:
    container_name: database-prod-${PROJECT_NAME}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - prod_data:/var/lib/postgresql/data

volumes:
  prod_data: {}
