---
version: '3.8'
services:
  django:
    build:
      target: development
    image: django-dev-${PROJECT_NAME}
    container_name: django-dev-${PROJECT_NAME}
    depends_on:
      - database
    volumes:
      - ../server:/myapp/:z
    environment:
      DATABASE_NAME: ${DEV_DATABASE_NAME}
    restart: always
  database:
    container_name: database-dev-${PROJECT_NAME}
    environment:
      POSTGRES_DB: ${DEV_DATABASE_NAME}
    restart: always
    volumes:
      - dev_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  dev_data: {}
  pgadmin-data: {}
